// <auto-generated />
using System;
using DwapiCentral.Prep.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DwapiCentral.Prep.Infrastructure.Migrations
{
    [DbContext(typeof(PrepDbContext))]
    partial class PrepDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Cargoes");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Docket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Dockets");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Facility", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateArrived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Docket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DwapiVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmrSetup")
                        .HasColumnType("int");

                    b.Property<string>("EmrVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Recieved")
                        .HasColumnType("int");

                    b.Property<Guid>("Session")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.MasterFacility", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("MasterFacilities");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", b =>
                {
                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientPreviouslyonPrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountyofBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastUsedPrev")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStartedPrEPattransferringfacility")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatefirstinitiatedinPrepCare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inschool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PrepEnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrevPrepReg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Refferedfrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferFromFacility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransferInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientPk", "SiteCode", "PrepNumber");

                    b.ToTable("PrepPatients");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepAdverseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdverseEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventActionTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventClinicalOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdverseEventEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdverseEventIsPregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdverseEventStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode", "PrepNumber");

                    b.ToTable("PrepAdverseEvents");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepBehaviourRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientAssessments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientWillingToTakePrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstEstablishPartnerStatus")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HIVPartnerARTStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HIVPartnerCCCnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsHIVPositivePartnerCurrentonART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsPartnerHighrisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthsknownHIVSerodiscordant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofchildrenWithPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerARTRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PartnerEnrolledtoCCC")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrEPDeclineReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralToOtherPrevServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskReductionEducationOffered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexPartnerHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexWithoutCondom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode", "PrepNumber");

                    b.ToTable("PrepBehaviourRisks");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepCareTermination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfLastPrepDose")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExitReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode", "PrepNumber");

                    b.ToTable("PrepCareTerminations");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepLab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SampleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TestResultDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode", "PrepNumber");

                    b.ToTable("PrepLabs");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepMonthlyRefill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdherenceCounsellingDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BehaviorRiskAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientGivenNextAppointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondomsIssued")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraIndicationForPrEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfLastPrepDose")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispenseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfCondomsIssued")
                        .HasColumnType("int");

                    b.Property<string>("NumberOfMonths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrescribedPrepToday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForFailureToGiveAppointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexPartnerHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SymptomsAcuteHIV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode", "PrepNumber");

                    b.ToTable("PrepMonthlyRefills");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepPharmacy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispenseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode", "PrepNumber");

                    b.ToTable("PrepPharmacys");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdherenceDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdherenceOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdherenceReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BirthDefects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breastfeeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Circumcised")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondomsIssued")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraindicationsPrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EDD")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncounterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FPMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyPlanningStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HepatitisBPositiveResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HepatitisCPositiveResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LMP")
                        .HasColumnType("datetime2");

                    b.Property<string>("MenopausalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthsPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAppointment")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PlanningToGetPregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PregnancyEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PregnancyEnded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PregnancyOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PregnancyPlanned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PregnantAtThisVisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrepPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepTreatmentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reasonfornotgivingnextappointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STIScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STISymptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STITreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SymptomsAcuteHIV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tobegivennextappointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatedForHepB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatedForHepC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VMMCReferral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccinationForHepBStarted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccinationForHepCStarted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode", "PrepNumber");

                    b.ToTable("PrepVisits");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Stage.StagePatientPrep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientPreviouslyonPrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountyofBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastUsedPrev")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStartedPrEPattransferringfacility")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatefirstinitiatedinPrepCare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inschool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PrepEnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrevPrepReg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Refferedfrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferFromFacility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransferInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StagePrepPatients");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Stage.StagePrepAdverseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdverseEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventActionTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventClinicalOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdverseEventEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdverseEventIsPregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdverseEventStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StagePrepAdverseEvents");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Stage.StagePrepBehaviourRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientAssessments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientWillingToTakePrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstEstablishPartnerStatus")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HIVPartnerARTStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HIVPartnerCCCnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsHIVPositivePartnerCurrentonART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsPartnerHighrisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MonthsknownHIVSerodiscordant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofchildrenWithPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerARTRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PartnerEnrolledtoCCC")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrEPDeclineReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralToOtherPrevServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskReductionEducationOffered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexPartnerHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexWithoutCondom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StagePrepBehaviourRisks");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Stage.StagePrepCareTermination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfLastPrepDose")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExitReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StagePrepCareTerminations");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Stage.StagePrepLab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SampleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TestResultDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StagePrepLabs");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Stage.StagePrepMonthlyRefill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdherenceCounsellingDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BehaviorRiskAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientGivenNextAppointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondomsIssued")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraIndicationForPrEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfLastPrepDose")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NumberOfCondomsIssued")
                        .HasColumnType("int");

                    b.Property<string>("NumberOfMonths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrescribedPrepToday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForFailureToGiveAppointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexPartnerHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SymptomsAcuteHIV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StagePrepMonthlyRefills");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Stage.StagePrepPharmacy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispenseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StagePrepPharmacys");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Stage.StagePrepVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdherenceDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdherenceOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdherenceReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BirthDefects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breastfeeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Circumcised")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondomsIssued")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraindicationsPrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EDD")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncounterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FPMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyPlanningStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HepatitisBPositiveResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HepatitisCPositiveResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LMP")
                        .HasColumnType("datetime2");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MenopausalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthsPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAppointment")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PlanningToGetPregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PregnancyEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PregnancyEnded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PregnancyOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PregnancyPlanned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PregnantAtThisVisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepTreatmentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reasonfornotgivingnextappointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenPrescribed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STIScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STISymptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STITreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SymptomsAcuteHIV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tobegivennextappointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatedForHepB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatedForHepC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VMMCReferral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccinationForHepBStarted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccinationForHepCStarted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("StagePrepVisits");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Subscriber", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocketId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Cargo", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.Manifest", null)
                        .WithMany("Cargoes")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepAdverseEvent", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", null)
                        .WithMany("PrepAdverseEvents")
                        .HasForeignKey("PatientPk", "SiteCode", "PrepNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepBehaviourRisk", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", null)
                        .WithMany("PrepBehaviourRisks")
                        .HasForeignKey("PatientPk", "SiteCode", "PrepNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepCareTermination", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", null)
                        .WithMany("PrepCareTerminations")
                        .HasForeignKey("PatientPk", "SiteCode", "PrepNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepLab", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", null)
                        .WithMany("PrepLabs")
                        .HasForeignKey("PatientPk", "SiteCode", "PrepNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepMonthlyRefill", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", null)
                        .WithMany("PrepMonthlyRefills")
                        .HasForeignKey("PatientPk", "SiteCode", "PrepNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepPharmacy", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", null)
                        .WithMany("PrepPharmacies")
                        .HasForeignKey("PatientPk", "SiteCode", "PrepNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PrepVisit", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", null)
                        .WithMany("PrepVisits")
                        .HasForeignKey("PatientPk", "SiteCode", "PrepNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Subscriber", b =>
                {
                    b.HasOne("DwapiCentral.Prep.Domain.Models.Docket", null)
                        .WithMany("Subscribers")
                        .HasForeignKey("DocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Docket", b =>
                {
                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.Manifest", b =>
                {
                    b.Navigation("Cargoes");
                });

            modelBuilder.Entity("DwapiCentral.Prep.Domain.Models.PatientPrepExtract", b =>
                {
                    b.Navigation("PrepAdverseEvents");

                    b.Navigation("PrepBehaviourRisks");

                    b.Navigation("PrepCareTerminations");

                    b.Navigation("PrepLabs");

                    b.Navigation("PrepMonthlyRefills");

                    b.Navigation("PrepPharmacies");

                    b.Navigation("PrepVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
