// <auto-generated />
using System;
using DwapiCentral.Ct.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DwapiCentral.Ct.Infrastructure.Migrations
{
    [DbContext(typeof(CtDbContext))]
    partial class CtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.AllergiesChronicIllnessExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abdomen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergicReaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergyCausativeAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AllergyOnsetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AllergySeverity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicIllness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChronicOnsetDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eyes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genitourinary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Skin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("knownAllergies")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("AllergiesChronicIllnessExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.ContactListingExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContactPatientPK")
                        .HasColumnType("int");

                    b.Property<string>("ContactSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentlyLivingWithIndexClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPVScreeningOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpvScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgeOfHivStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartnerPersonID")
                        .HasColumnType("int");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PnsApproach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipWithPatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenedForIpv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("contactListingExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.CovidExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AdmissionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AdmissionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdmissionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionStatusSinceLastVisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionUnitSinceLastVisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoosterDose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BoosterDoseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BoosterDoseVerified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoosterGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COVID19PositiveSinceLasVisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("COVID19TestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("COVID19TestDateSinceLastVisit")
                        .HasColumnType("datetime2");

                    b.Property<string>("COVID19TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Covid19AssessmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateGivenFirstDose")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateGivenSecondDose")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EverCOVID19Positive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstDoseVaccineAdministered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissedAppointmentDueToCOVID19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PatientStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientStatusSinceLastVisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientVentilated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedCOVID19Vaccine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondDoseVaccineAdministered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SupplementalOxygenReceived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TracingFinalOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaccinationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccineVerification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("CovidExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.DefaulterTracingExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CauseOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsFinalTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("TracingOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TracingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrueStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("DefaulterTracingExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.DepressionScreeningExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepressionAssesmentScore")
                        .HasColumnType("int");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ9_9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHQ_9_rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("DepressionScreeningExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.DrugAlcoholScreeningExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrinkingAlcohol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Smoking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("DrugAlcoholScreeningExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.EnhancedAdherenceCounsellingExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfFirstSession")
                        .HasColumnType("datetime2");

                    b.Property<string>("EACAdherencePlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACBehaviouralBarrier_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACBehaviouralBarrier_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACBehaviouralBarrier_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACBehaviouralBarrier_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACBehaviouralBarrier_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACCognitiveBarrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEconBarrier_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEconBarrier_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEconBarrier_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEconBarrier_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEconBarrier_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEconBarrier_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEconBarrier_7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEconBarrier_8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEmotionalBarriers_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACEmotionalBarriers_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EACFollowupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EACHomevisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACRecievedVL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACReferral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACReferralApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACReferralExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACReviewImprovement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACReviewMissedDoses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACReviewStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACVL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACVLConcerns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACVLThoughts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EACWayForward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMAS4_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMAS4_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMAS4_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMAS4_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMSA8_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMSA8_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMSA8_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMSA8_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMSAScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int?>("PillCountAdherence")
                        .HasColumnType("int");

                    b.Property<int?>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("EnhancedAdherenceCounsellingExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.GbvScreeningExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmotionalIPV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPVRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PhysicalIPV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexualIPV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("GbvScreeningExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.IptExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactsInvited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluatedForIPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverOnIPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fever")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICFActionTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPTClientWorkUp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicationForIPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lethargy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NightSweats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoticeableWeightLoss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnIPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnTBDrugs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("StartAntiTBs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartIPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TBClinicalDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TBRxStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TBScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("IptExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.OtzExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModulesCompletedToday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModulesPreviouslyCovered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OTZEnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OutcomeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SupportGroupInvolvement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferInStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransitionAttritionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("OtzExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.OvcExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPIMSUniqueIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrolledinCPIMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OVCEnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OVCExitReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerOfferingOVCServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipToClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("OvcExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientAdverseEventExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdverseEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventActionTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventClinicalOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdverseEventEndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("AdverseEventIsPregnant")
                        .HasColumnType("bit");

                    b.Property<string>("AdverseEventRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdverseEventStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("PatientAdverseEventExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientArtExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AgeARTStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AgeEnrollment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AgeLastVisit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastUsed")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExitReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedReturn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastARTDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastRegimenLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PatientSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousARTPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousARTRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PreviousARTStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousARTUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartARTAtThisFacility")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartARTDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartRegimenLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("PatientArtExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientBaselinesExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<int?>("bCD4")
                        .HasColumnType("int");

                    b.Property<DateTime?>("bCD4Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("bWAB")
                        .HasColumnType("int");

                    b.Property<DateTime?>("bWABDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("bWHO")
                        .HasColumnType("int");

                    b.Property<DateTime?>("bWHODate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("eCD4")
                        .HasColumnType("int");

                    b.Property<DateTime?>("eCD4Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("eWAB")
                        .HasColumnType("int");

                    b.Property<DateTime?>("eWABDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("eWHO")
                        .HasColumnType("int");

                    b.Property<DateTime?>("eWHODate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("lastCD4")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastCD4Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("lastWAB")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastWABDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("lastWHO")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastWHODate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("m12CD4")
                        .HasColumnType("int");

                    b.Property<DateTime?>("m12CD4Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("m6CD4")
                        .HasColumnType("int");

                    b.Property<DateTime?>("m6CD4Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("PatientBaselinesExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", b =>
                {
                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("CccNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateConfirmedHIVPositive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inschool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MpiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nupi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orphan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientResidentCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientResidentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientResidentSubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientResidentSubLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientResidentVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientResidentWard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pkv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousARTExposure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PreviousARTStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationATPMTCT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationAtCCC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationAtTBClinic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusAtCCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusAtPMTCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusAtTBClinic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransferInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Village")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("PatientPk", "SiteCode");

                    b.ToTable("PatientExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientLaboratoryExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSampleTaken")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnrollmentTest")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderedByDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReportedByDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SampleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("PatientLaboratoryExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientPharmacyExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DispenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpectedReturn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PeriodTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProphylaxisType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenChangeSwitchReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenChangedSwitched")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StopRegimenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StopRegimenReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("PatientPharmacyExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientStatusExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDiscontinuationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExitDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReEnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonForDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SpecificDeathReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOVerified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TOVerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("PatientStatusExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientVisitExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abdomen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adherence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdherenceCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breastfeeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTXAdherence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DifferentiatedCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EDD")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverHadMenses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eyes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyPlanningMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genitourinary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GestationAge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HCWConcern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KeyPopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LMP")
                        .HasColumnType("datetime2");

                    b.Property<string>("Menopausal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Muac")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextAppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoFPReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OIDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OxygenSaturation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProphylaxisUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PulseRate")
                        .HasColumnType("int");

                    b.Property<string>("PwP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefillDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SecondlineRegimenChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondlineRegimenChangeReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Skin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StabilityAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubstitutionFirstlineRegimenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubstitutionFirstlineRegimenReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubstitutionSecondlineRegimenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubstitutionSecondlineRegimenReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCAReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Temp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("WABStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WHOStage")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("PatientVisitExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Facility", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Docket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DwapiVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmrSetup")
                        .HasColumnType("int");

                    b.Property<string>("EmrVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Session")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.MasterFacility", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("MasterFacilities");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.AllergiesChronicIllnessExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("AllergiesChronicIllnessExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.ContactListingExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("ContactListingExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.CovidExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("CovidExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.DefaulterTracingExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("DefaulterTracingExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.DepressionScreeningExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("DepressionScreeningExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.DrugAlcoholScreeningExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("DrugAlcoholScreeningExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.EnhancedAdherenceCounsellingExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("EnhancedAdherenceCounsellingExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.GbvScreeningExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("GbvScreeningExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.IptExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("IptExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.OtzExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("OtzExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.OvcExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("OvcExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientAdverseEventExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("PatientAdverseEventExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientArtExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("PatientArtExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientBaselinesExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("PatientBaselinesExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientLaboratoryExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("PatientLaboratoryExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientPharmacyExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("PatientPharmacyExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientStatusExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("PatientStatusExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientVisitExtract", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", null)
                        .WithMany("PatientVisitExtracts")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Metric", b =>
                {
                    b.HasOne("DwapiCentral.Ct.Domain.Models.Manifest", null)
                        .WithMany("Metrics")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Extracts.PatientExtract", b =>
                {
                    b.Navigation("AllergiesChronicIllnessExtracts");

                    b.Navigation("ContactListingExtracts");

                    b.Navigation("CovidExtracts");

                    b.Navigation("DefaulterTracingExtracts");

                    b.Navigation("DepressionScreeningExtracts");

                    b.Navigation("DrugAlcoholScreeningExtracts");

                    b.Navigation("EnhancedAdherenceCounsellingExtracts");

                    b.Navigation("GbvScreeningExtracts");

                    b.Navigation("IptExtracts");

                    b.Navigation("OtzExtracts");

                    b.Navigation("OvcExtracts");

                    b.Navigation("PatientAdverseEventExtracts");

                    b.Navigation("PatientArtExtracts");

                    b.Navigation("PatientBaselinesExtracts");

                    b.Navigation("PatientLaboratoryExtracts");

                    b.Navigation("PatientPharmacyExtracts");

                    b.Navigation("PatientStatusExtracts");

                    b.Navigation("PatientVisitExtracts");
                });

            modelBuilder.Entity("DwapiCentral.Ct.Domain.Models.Manifest", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
