// <auto-generated />
using System;
using DwapiCentral.Hts.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DwapiCentral.Hts.Infrastructure.Migrations
{
    [DbContext(typeof(HtsDbContext))]
    [Migration("20240207134734__initialHtsMigration")]
    partial class _initialHtsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Cargoes");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Docket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Dockets");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Facility", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsClient", b =>
                {
                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsRecencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyPopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientDisabled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pkv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityPopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientPk", "SiteCode");

                    b.ToTable("HtsClients");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsClientLinkage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnrolled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePrefferedToBeEnrolled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrolledFacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityReferredTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandedOverTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandedOverToCadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReferralDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedCCCNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReportedStartARTDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("HtsClientLinkages");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsClientTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Approach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSelfTested")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientTestedAs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoupleDiscordant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("EntryPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverTestedForHiv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalTestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsRiskCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HtsRiskScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MonthsSinceLastTest")
                        .HasColumnType("int");

                    b.Property<string>("PatientGivenResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TbScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestResult1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("HtsClientTests");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsClientTracing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TracingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TracingOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TracingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("HtsClientTracing");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsEligibilityScreening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlcoholSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssessmentOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreastfeedingMother")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildReasonsForIneligibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondomBurst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactWithTBCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoupleDiscordant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentlyHasSTI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyOnPep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyOnPrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTestedProvider")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTestedSelf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisabilityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EligibleForTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverHadSTI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverHadSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverHadTB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverOnPep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverOnPrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperiencedGBV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fever")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForcedSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVRiskCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTSEntryPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTSStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsRiskScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsHealthWorker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPopulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnownStatusPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lethargy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoneySex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MothersStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultiplePartners")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedleStickInjuries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NightSweats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfPartners")
                        .HasColumnType("int");

                    b.Property<string>("PartnerHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PatientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityPopulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonNotReffered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonRefferredForTesting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonsForIneligibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredForTesting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipWithContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultOfHIV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultOfHIVSelf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenedTB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexuallyActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharedNeedle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<int?>("SpecificReasonForIneligibility")
                        .HasColumnType("int");

                    b.Property<string>("StartedOnART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TBStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestedHIVBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraditionalProcedures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeGBV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnknownStatusPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("WeightLoss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoPerformedTest")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("HtsEligibilityExtract");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsPartnerNotificationServices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CccNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentlyLivingWithIndexClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateElicited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityLinkedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpvScreeningOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgeOfHivStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LinkDateLinkedToCare")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedToCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartnerPatientPk")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerPersonID")
                        .HasColumnType("int");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PnsApproach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PnsConsent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationsipToIndexClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenedForIpv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("HtsPartnerNotificationServices");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsPartnerTracing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartnerPersonId")
                        .HasColumnType("int");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TraceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TraceOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("HtsPartnerTracings");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsTestKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SyphilisResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitExpiry1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitExpiry2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitLotNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitLotNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPk", "SiteCode");

                    b.ToTable("HtsTestKits");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateArrived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Docket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DwapiVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmrSetup")
                        .HasColumnType("int");

                    b.Property<string>("EmrVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManifestStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Recieved")
                        .HasColumnType("int");

                    b.Property<int>("Sent")
                        .HasColumnType("int");

                    b.Property<Guid>("Session")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.MasterFacility", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("MasterFacilities");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Stage.StageHtsClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Extracted")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsRecencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientDisabled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("Pkv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityPopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StageClients");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Stage.StageHtsClientLinkage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnrolled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePrefferedToBeEnrolled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrolledFacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityReferredTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandedOverTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandedOverToCadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReferralDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedCCCNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReportedStartARTDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StageClientLinkages");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Stage.StageHtsClientTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Approach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSelfTested")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientTestedAs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoupleDiscordant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("EntryPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverTestedForHiv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalTestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsRiskCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HtsRiskScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MonthsSinceLastTest")
                        .HasColumnType("int");

                    b.Property<string>("PatientGivenResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TbScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestResult1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StageHtsClientTests");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Stage.StageHtsClientTracing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TracingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TracingOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TracingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StageHtsClientTracing");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Stage.StageHtsEligibilityScreening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlcoholSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssessmentOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreastfeedingMother")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildReasonsForIneligibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondomBurst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactWithTBCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoupleDiscordant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentlyHasSTI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyOnPep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyOnPrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTestedProvider")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTestedSelf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisabilityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EligibleForTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncounterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverHadSTI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverHadSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverHadTB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverOnPep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EverOnPrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperiencedGBV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fever")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForcedSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVRiskCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTSEntryPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTSStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsRiskScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsHealthWorker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPopulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnownStatusPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lethargy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoneySex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MothersStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultiplePartners")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedleStickInjuries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NightSweats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfPartners")
                        .HasColumnType("int");

                    b.Property<string>("PartnerHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PatientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityPopulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonNotReffered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonRefferredForTesting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonsForIneligibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredForTesting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipWithContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultOfHIV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultOfHIVSelf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenedTB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexuallyActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharedNeedle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<int?>("SpecificReasonForIneligibility")
                        .HasColumnType("int");

                    b.Property<string>("StartedOnART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TBStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestedHIVBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraditionalProcedures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeGBV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnknownStatusPartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("WeightLoss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoPerformedTest")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StageHtsEligibilityExtract");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Stage.StageHtsPartnerNotificationServices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CccNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentlyLivingWithIndexClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateElicited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityLinkedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpvScreeningOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgeOfHivStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LinkDateLinkedToCare")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedToCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartnerPatientPk")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerPersonID")
                        .HasColumnType("int");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PnsApproach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PnsConsent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationsipToIndexClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenedForIpv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StageHtsPartnerNotificationServices");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Stage.StageHtsPartnerTracing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PartnerPersonId")
                        .HasColumnType("int");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TraceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TraceOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StageHtsPartnerTracings");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Stage.StageHtsTestKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiveStage")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("RecordUUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SyphilisResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitExpiry1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitExpiry2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitLotNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitLotNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKitName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StageHtsTestKits");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocketId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Cargo", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.Manifest", null)
                        .WithMany("Cargoes")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsClientLinkage", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.HtsClient", null)
                        .WithMany("HtsClientLinkages")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsClientTest", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.HtsClient", null)
                        .WithMany("HtsClientTestss")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsClientTracing", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.HtsClient", null)
                        .WithMany("HtsClientTracings")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsEligibilityScreening", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.HtsClient", null)
                        .WithMany("HtsClientPartners")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsPartnerNotificationServices", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.HtsClient", null)
                        .WithMany("HtsPartnerNotificationServicess")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsPartnerTracing", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.HtsClient", null)
                        .WithMany("HtsPartnerTracings")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsTestKit", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.HtsClient", null)
                        .WithMany("HtsTestKitss")
                        .HasForeignKey("PatientPk", "SiteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Subscriber", b =>
                {
                    b.HasOne("DwapiCentral.Hts.Domain.Model.Docket", null)
                        .WithMany("Subscribers")
                        .HasForeignKey("DocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Docket", b =>
                {
                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.HtsClient", b =>
                {
                    b.Navigation("HtsClientLinkages");

                    b.Navigation("HtsClientPartners");

                    b.Navigation("HtsClientTestss");

                    b.Navigation("HtsClientTracings");

                    b.Navigation("HtsPartnerNotificationServicess");

                    b.Navigation("HtsPartnerTracings");

                    b.Navigation("HtsTestKitss");
                });

            modelBuilder.Entity("DwapiCentral.Hts.Domain.Model.Manifest", b =>
                {
                    b.Navigation("Cargoes");
                });
#pragma warning restore 612, 618
        }
    }
}
